import type { Contact } from './types';

/**
 * Baseline contact identities shared across modules. The Contacts module will
 * extend this fixture set; other modules must reference these IDs rather than
 * inventing their own customer records.
 */
export const contacts: Contact[] = [
  {
    id: 'contact_rahul_shah',
    name: 'Rahul Shah',
    company: 'Shah Textiles',
    mobile: '+919810011234',
    email: 'rahul@shahtextiles.example',
    city: 'New Delhi',
    ownerId: 'user_meera',
    stage: 'qualified',
    tags: ['bulk-buyer', 'festive-2026'],
    source: 'WhatsApp enquiry',
    consent: 'opted-in',
    salesTier: 'gold',
    branchId: 'branch_delhi',
    primaryWhatsAppNumberId: 'wa_delhi_sales',
    createdAt: '2026-01-14T09:20:00+05:30',
    lastActivityAt: '2026-08-07T16:42:00+05:30',
  },
  {
    id: 'contact_priya_menon',
    name: 'Priya Menon',
    company: null,
    mobile: '+919820022345',
    email: 'priya.menon@example.com',
    city: 'Mumbai',
    ownerId: 'user_vikram',
    stage: 'customer',
    tags: ['repeat', 'premium'],
    source: 'Website form',
    consent: 'opted-in',
    salesTier: 'platinum',
    branchId: 'branch_mumbai',
    primaryWhatsAppNumberId: 'wa_mumbai_sales',
    createdAt: '2025-11-02T11:05:00+05:30',
    lastActivityAt: '2026-08-09T10:15:00+05:30',
  },
  {
    id: 'contact_arjun_verma',
    name: 'Arjun Verma',
    company: 'Verma Interiors',
    mobile: '+919810033456',
    email: null,
    city: 'Gurugram',
    ownerId: 'user_meera',
    stage: 'engaged',
    tags: ['project-enquiry'],
    source: 'Referral',
    consent: 'pending',
    salesTier: 'silver',
    branchId: 'branch_delhi',
    primaryWhatsAppNumberId: 'wa_delhi_sales',
    createdAt: '2026-05-21T14:30:00+05:30',
    lastActivityAt: '2026-08-08T09:05:00+05:30',
  },
  {
    id: 'contact_sneha_iyer',
    name: 'Sneha Iyer',
    company: 'Iyer & Co.',
    mobile: '+919686044567',
    email: 'sneha@iyerco.example',
    city: 'Bengaluru',
    ownerId: 'user_vikram',
    stage: 'new',
    tags: ['inbound'],
    source: 'Campaign click',
    consent: 'opted-in',
    salesTier: 'standard',
    branchId: 'branch_bengaluru',
    primaryWhatsAppNumberId: 'wa_bengaluru_service',
    createdAt: '2026-08-05T18:12:00+05:30',
    lastActivityAt: '2026-08-06T12:00:00+05:30',
  },
  {
    id: 'contact_imran_qureshi',
    name: 'Imran Qureshi',
    company: 'Qureshi Motors',
    mobile: '+919810055678',
    email: 'imran@qureshimotors.example',
    city: 'Noida',
    ownerId: 'user_meera',
    stage: 'dormant',
    tags: ['lapsed'],
    source: 'Import — Jan 2026',
    consent: 'opted-out',
    salesTier: 'standard',
    branchId: 'branch_delhi',
    primaryWhatsAppNumberId: 'wa_delhi_support',
    createdAt: '2026-01-09T08:00:00+05:30',
    lastActivityAt: '2026-03-18T15:22:00+05:30',
  },
  {
    id: 'contact_kavita_desai',
    name: 'Kavita Desai',
    company: 'Desai Exports',
    mobile: '+919820066789',
    email: 'kavita@desaiexports.example',
    city: 'Thane',
    ownerId: 'user_vikram',
    stage: 'qualified',
    tags: ['export', 'high-value'],
    source: 'Trade show',
    consent: 'opted-in',
    salesTier: 'gold',
    branchId: 'branch_mumbai',
    primaryWhatsAppNumberId: 'wa_mumbai_sales',
    createdAt: '2026-04-11T10:40:00+05:30',
    lastActivityAt: '2026-08-09T17:30:00+05:30',
  },
  {
    id: 'contact_neha_gupta',
    name: 'Neha Gupta',
    company: null,
    mobile: '+919810077890',
    email: 'neha.gupta@example.com',
    city: 'New Delhi',
    ownerId: 'user_meera',
    stage: 'engaged',
    tags: ['festive-2026', 'inbound'],
    source: 'Campaign click',
    consent: 'opted-in',
    salesTier: 'silver',
    branchId: 'branch_delhi',
    primaryWhatsAppNumberId: 'wa_delhi_sales',
    createdAt: '2026-07-19T12:10:00+05:30',
    lastActivityAt: '2026-08-08T14:20:00+05:30',
  },
  {
    id: 'contact_rohit_malhotra',
    name: 'Rohit Malhotra',
    company: 'Malhotra Traders',
    mobile: '+919820088901',
    email: null,
    city: 'Mumbai',
    // System-created inbound contact still awaiting owner assignment.
    ownerId: '',
    stage: 'new',
    tags: [],
    source: 'Walk-in register',
    consent: 'pending',
    salesTier: 'standard',
    branchId: 'branch_mumbai',
    primaryWhatsAppNumberId: 'wa_mumbai_sales',
    createdAt: '2026-08-08T10:05:00+05:30',
    lastActivityAt: '2026-08-08T10:05:00+05:30',
  },
  {
    id: 'contact_ananya_reddy',
    name: 'Ananya Reddy',
    company: 'Reddy Jewels',
    mobile: '+919686099012',
    email: 'ananya@reddyjewels.example',
    city: 'Bengaluru',
    ownerId: 'user_anita',
    stage: 'customer',
    tags: ['premium', 'repeat'],
    source: 'Referral',
    consent: 'opted-in',
    salesTier: 'platinum',
    branchId: 'branch_bengaluru',
    primaryWhatsAppNumberId: 'wa_bengaluru_service',
    createdAt: '2025-12-15T09:30:00+05:30',
    lastActivityAt: '2026-08-09T11:45:00+05:30',
  },
  {
    id: 'contact_farhan_ali',
    name: 'Farhan Ali',
    company: null,
    mobile: '+919810100123',
    email: null,
    city: 'Faridabad',
    // Unnamed inbound enquiry, not yet routed to an owner.
    ownerId: '',
    stage: 'new',
    tags: ['unnamed-inbound'],
    source: 'WhatsApp enquiry',
    consent: 'pending',
    salesTier: 'standard',
    branchId: 'branch_delhi',
    primaryWhatsAppNumberId: 'wa_delhi_support',
    createdAt: '2026-08-09T19:02:00+05:30',
    lastActivityAt: '2026-08-09T19:02:00+05:30',
  },
  {
    id: 'contact_deepa_krishnan',
    name: 'Deepa Krishnan',
    company: 'Krishnan Textiles',
    mobile: '+919820111234',
    email: 'deepa@krishnantextiles.example',
    city: 'Pune',
    ownerId: 'user_vikram',
    stage: 'engaged',
    tags: ['bulk-buyer'],
    source: 'Website form',
    consent: 'opted-in',
    salesTier: 'silver',
    branchId: 'branch_mumbai',
    primaryWhatsAppNumberId: 'wa_mumbai_sales',
    createdAt: '2026-06-02T15:20:00+05:30',
    lastActivityAt: '2026-08-07T09:15:00+05:30',
  },
  {
    id: 'contact_sameer_joshi',
    name: 'Sameer Joshi',
    company: 'Joshi Motors',
    mobile: '+919810122345',
    email: 'sameer@joshimotors.example',
    city: 'New Delhi',
    ownerId: 'user_meera',
    stage: 'dormant',
    tags: ['lapsed'],
    source: 'Import — Jan 2026',
    consent: 'opted-out',
    salesTier: 'standard',
    branchId: 'branch_delhi',
    primaryWhatsAppNumberId: 'wa_delhi_sales',
    createdAt: '2026-01-20T08:45:00+05:30',
    lastActivityAt: '2026-04-02T13:10:00+05:30',
  },
];

export function findContact(contactId: string): Contact | undefined {
  return contacts.find((contact) => contact.id === contactId);
}

/** Contacts visible within a branch/number scope (all when scope is null). */
export function contactsInScope(scope: {
  branchId?: string | null;
  whatsappNumberId?: string | null;
}): Contact[] {
  return contacts.filter((contact) => {
    const branchOk = !scope.branchId || contact.branchId === scope.branchId;
    const numberOk =
      !scope.whatsappNumberId || contact.primaryWhatsAppNumberId === scope.whatsappNumberId;
    return branchOk && numberOk;
  });
}
