import type { CrmContact } from '@prisma/client';

/**
 * Serialize a CrmContact row into the prototype's Contact shape, including the
 * requirement additions (B2B/B2C, lead status vs lifecycle, enrichment,
 * geography, interests). Shared by the bootstrap and contact APIs.
 */
export function serializeCrmContact(c: CrmContact) {
  return {
    id: c.id,
    name: c.name,
    company: c.company,
    mobile: c.mobile,
    email: c.email,
    city: c.city,
    ownerId: c.ownerId,
    stage: c.stage,
    tags: c.tags,
    source: c.source,
    consent: c.consent,
    salesTier: c.salesTier,
    branchId: c.branchId,
    primaryWhatsAppNumberId: c.primaryWhatsAppNumberId,
    createdAt: c.createdAt.toISOString(),
    lastActivityAt: c.lastActivityAt.toISOString(),
    customerType: c.customerType,
    contactPerson: c.contactPerson,
    leadStatus: c.leadStatus,
    lifecycleStage: c.lifecycleStage,
    lifecycleState: c.lifecycleState,
    activatedAt: c.activatedAt ? c.activatedAt.toISOString() : null,
    gstin: c.gstin,
    legalName: c.legalName,
    billingAddress: c.billingAddress,
    shippingAddress: c.shippingAddress,
    state: c.state,
    zone: c.zone,
    pincode: c.pincode,
    productInterests: c.productInterests,
    businessValue: c.businessValue,
    consentOptInSource: c.consentOptInSource,
    consentOptInAt: c.consentOptInAt ? c.consentOptInAt.toISOString() : null,
    // --- Jewellery B2B enrichment ---
    businessSegment: c.businessSegment,
    grade: c.grade,
    preferredLanguage: c.preferredLanguage,
    website: c.website,
    dateOfBirth: c.dateOfBirth ? c.dateOfBirth.toISOString() : null,
    companyAnniversary: c.companyAnniversary ? c.companyAnniversary.toISOString() : null,
    nextFollowUpAt: c.nextFollowUpAt ? c.nextFollowUpAt.toISOString() : null,
    interestedIn: c.interestedIn,
    lastFeedback: c.lastFeedback,
    lastConnectAt: c.lastConnectAt ? c.lastConnectAt.toISOString() : null,
    clientCode: c.clientCode,
    pan: c.pan,
    kamUserId: c.kamUserId,
    dataVerified: c.dataVerified,
    introCallDone: c.introCallDone,
    officeVisitDone: c.officeVisitDone,
    inBroadcastList: c.inBroadcastList,
    inCommunity: c.inCommunity,
    jewelleryProfile: c.jewelleryProfile ?? null,
  };
}
