/**
 * Deterministic Inbox mock data — 10 conversation scenarios required by SKILL.md Batch 0.
 * All timestamps relative to reference date 2026-08-10T10:00:00+05:30.
 * IDs are stable so Figma captures of the same ?conversation= route are identical.
 */

import type {
  InboxConversation,
  InboxMessage,
  InboxTemplate,
  ConversationLabel,
  QuickReply,
  AiSuggestedTask,
  ConversationActivityEvent,
  InboxAnalytics,
} from './inbox-types';

// ---- Conversation labels ---------------------------------------------------

export const conversationLabels: ConversationLabel[] = [
  { id: 'lbl_hot_lead', name: 'Hot Lead', color: '#b0453f', scope: 'workspace', teamId: null },
  { id: 'lbl_follow_up', name: 'Follow-up', color: '#b8892b', scope: 'workspace', teamId: null },
  { id: 'lbl_bulk_enquiry', name: 'Bulk Enquiry', color: '#1b7a6b', scope: 'workspace', teamId: null },
  { id: 'lbl_support', name: 'Support', color: '#4a5d6e', scope: 'workspace', teamId: null },
  { id: 'lbl_payment', name: 'Payment Issue', color: '#c9a227', scope: 'team', teamId: 'team_delhi_support' },
  { id: 'lbl_vip', name: 'VIP', color: '#9c7d19', scope: 'workspace', teamId: null },
];

export function findLabel(id: string): ConversationLabel | undefined {
  return conversationLabels.find((l) => l.id === id);
}

// ---- Quick replies ---------------------------------------------------------

export const quickReplies: QuickReply[] = [
  {
    id: 'qr_greeting',
    name: 'Warm Greeting',
    content: 'Hi {{1}}, thanks for reaching out to Northline Retail! How can I help you today?',
    category: 'Greetings',
    language: 'en',
    scope: 'workspace',
    ownerId: null,
    hasVariables: true,
    variables: ['customer_name'],
  },
  {
    id: 'qr_pricing',
    name: 'Pricing — Bulk Enquiry',
    content:
      "For bulk orders above 50 units, we offer special pricing. I'll send you our current catalogue. Please share your requirements and target quantity.",
    category: 'Sales',
    language: 'en',
    scope: 'workspace',
    ownerId: null,
    hasVariables: false,
    variables: [],
  },
  {
    id: 'qr_payment_followup',
    name: 'Payment Follow-up',
    content:
      'Hi {{1}}, I wanted to follow up on the pending payment for order #{{2}}. Please let us know if you need any assistance.',
    category: 'Payments',
    language: 'en',
    scope: 'team',
    ownerId: 'team_delhi_support',
    hasVariables: true,
    variables: ['customer_name', 'order_id'],
  },
  {
    id: 'qr_out_of_office',
    name: 'Out of Office',
    content:
      'Thank you for your message. Our team is currently unavailable. We will respond within 2 business hours. For urgent queries, call +91 98110 20001.',
    category: 'Greetings',
    language: 'en',
    scope: 'workspace',
    ownerId: null,
    hasVariables: false,
    variables: [],
  },
  {
    id: 'qr_closing',
    name: 'Closing — Resolved',
    content:
      'Happy to help, {{1}}! If you have any other questions, feel free to reach out. Have a great day!',
    category: 'Closing',
    language: 'en',
    scope: 'workspace',
    ownerId: null,
    hasVariables: true,
    variables: ['customer_name'],
  },
];

// ---- Message templates ----------------------------------------------------

export const inboxTemplates: InboxTemplate[] = [
  {
    id: 'tmpl_welcome_intro',
    name: 'welcome_intro',
    displayName: 'Welcome Introduction',
    category: 'utility',
    language: 'en',
    status: 'approved',
    headerType: 'text',
    headerText: 'Welcome to Northline Retail!',
    bodyText:
      "Hi {{1}}, we're glad to have you reach out! I'm {{2}} from the {{3}} team. How can we assist you today?",
    footer: 'Northline Retail — Making quality accessible.',
    variables: ['customer_name', 'agent_name', 'team_name'],
    buttons: [{ type: 'quick-reply', label: 'Browse Catalogue' }, { type: 'quick-reply', label: 'Talk to Agent' }],
    numberIds: [],
  },
  {
    id: 'tmpl_appointment_reminder',
    name: 'appointment_reminder',
    displayName: 'Appointment Reminder',
    category: 'utility',
    language: 'en',
    status: 'approved',
    headerType: 'none',
    bodyText:
      'Hi {{1}}, this is a reminder for your appointment on {{2}} at {{3}}. Please confirm your attendance or let us know if you need to reschedule.',
    footer: 'Northline Retail Support',
    variables: ['customer_name', 'date', 'time'],
    buttons: [{ type: 'quick-reply', label: 'Confirm' }, { type: 'quick-reply', label: 'Reschedule' }],
    numberIds: [],
  },
  {
    id: 'tmpl_order_shipped',
    name: 'order_shipped',
    displayName: 'Order Shipped',
    category: 'utility',
    language: 'en',
    status: 'approved',
    headerType: 'text',
    headerText: 'Your order is on its way!',
    bodyText:
      'Great news, {{1}}! Your order #{{2}} has been shipped. Expected delivery: {{3}}. Track your shipment using the link below.',
    variables: ['customer_name', 'order_id', 'delivery_date'],
    buttons: [{ type: 'url', label: 'Track Order', value: 'https://tracking.northline.in/{{2}}' }],
    numberIds: [],
  },
  {
    id: 'tmpl_payment_reminder',
    name: 'payment_reminder',
    displayName: 'Payment Reminder',
    category: 'utility',
    language: 'en',
    status: 'approved',
    headerType: 'none',
    bodyText:
      'Hi {{1}}, we noticed your payment of ₹{{2}} for order #{{3}} is due on {{4}}. Please complete the payment to avoid delays in order processing.',
    footer: 'Northline Retail Accounts',
    variables: ['customer_name', 'amount', 'order_id', 'due_date'],
    buttons: [{ type: 'url', label: 'Pay Now', value: 'https://pay.northline.in/{{3}}' }],
    numberIds: ['wa_delhi_support'],
  },
  {
    id: 'tmpl_feedback_request',
    name: 'feedback_request',
    displayName: 'Feedback Request',
    category: 'marketing',
    language: 'en',
    status: 'approved',
    headerType: 'none',
    bodyText:
      "Hi {{1}}, hope your recent experience with Northline Retail was great! We'd love to hear your feedback. It takes just 2 minutes and helps us serve you better.",
    variables: ['customer_name'],
    buttons: [{ type: 'url', label: 'Share Feedback', value: 'https://feedback.northline.in/{{1}}' }],
    numberIds: [],
  },
  {
    id: 'tmpl_otp_verify',
    name: 'otp_verify',
    displayName: 'OTP Verification',
    category: 'authentication',
    language: 'en',
    status: 'approved',
    headerType: 'none',
    bodyText: 'Your Northline Retail verification code is {{1}}. This code expires in 10 minutes. Do not share it with anyone.',
    variables: ['otp_code'],
    buttons: [],
    numberIds: [],
  },
  {
    id: 'tmpl_restock_alert',
    name: 'restock_alert',
    displayName: 'Back in Stock Alert',
    category: 'marketing',
    language: 'en',
    status: 'pending',
    headerType: 'none',
    bodyText: "Great news, {{1}}! The item you were interested in — {{2}} — is back in stock. Order now before it sells out again!",
    variables: ['customer_name', 'product_name'],
    buttons: [{ type: 'quick-reply', label: 'Order Now' }],
    numberIds: [],
  },
];

export function findTemplate(id: string): InboxTemplate | undefined {
  return inboxTemplates.find((t) => t.id === id);
}

// ---- Conversations ---------------------------------------------------------
// Scenario 1: Normal active conversation — Rahul Shah / Meera / Delhi Sales

export const conv_rahul_active: InboxConversation = {
  id: 'conv_rahul_active',
  contactId: 'contact_rahul_shah',
  rawMobile: null,
  whatsappNumberId: 'wa_delhi_sales',
  assigneeId: 'user_meera',
  teamId: 'team_delhi_sales',
  botOwned: false,
  status: 'open',
  unreadCount: 2,
  labelIds: ['lbl_bulk_enquiry', 'lbl_hot_lead'],
  replyStatus: 'awaiting-agent',
  responseWindow: {
    status: 'active',
    expiresAt: '2026-08-10T22:42:00+05:30',
    remainingMinutes: 762,
    canSendFreeform: true,
  },
  sla: { status: 'warning', deadline: '2026-08-10T11:00:00+05:30', minutesRemaining: 58 },
  preview: {
    text: 'Can you confirm if the summer collection is still in stock?',
    isIncoming: true,
    isNote: false,
    at: '2026-08-10T09:42:00+05:30',
  },
  isSpam: false,
  aiTaskCount: 0,
  firstMessageAt: '2026-08-10T09:20:00+05:30',
  lastMessageAt: '2026-08-10T09:42:00+05:30',
};

// Scenario 2: Unknown customer — no Contact record

export const conv_unknown_number: InboxConversation = {
  id: 'conv_unknown_9911',
  contactId: null,
  rawMobile: '+91 99112 99001',
  whatsappNumberId: 'wa_delhi_sales',
  assigneeId: null,
  teamId: null,
  botOwned: false,
  status: 'open',
  unreadCount: 1,
  labelIds: [],
  replyStatus: 'awaiting-agent',
  responseWindow: {
    status: 'active',
    expiresAt: '2026-08-10T20:10:00+05:30',
    remainingMinutes: 610,
    canSendFreeform: true,
  },
  sla: { status: 'ok', deadline: '2026-08-10T12:10:00+05:30', minutesRemaining: 130 },
  preview: {
    text: 'Hello, I want to place a bulk order for Diwali gifting.',
    isIncoming: true,
    isNote: false,
    at: '2026-08-10T08:10:00+05:30',
  },
  isSpam: false,
  aiTaskCount: 0,
  firstMessageAt: '2026-08-10T08:10:00+05:30',
  lastMessageAt: '2026-08-10T08:10:00+05:30',
};

// Scenario 3: Expired response window — Priya Menon / Vikram

export const conv_priya_expired: InboxConversation = {
  id: 'conv_priya_expired',
  contactId: 'contact_priya_menon',
  rawMobile: null,
  whatsappNumberId: 'wa_mumbai_sales',
  assigneeId: 'user_vikram',
  teamId: 'team_mumbai_sales',
  botOwned: false,
  status: 'open',
  unreadCount: 0,
  labelIds: ['lbl_vip'],
  replyStatus: 'awaiting-agent',
  responseWindow: {
    status: 'expired',
    expiresAt: '2026-08-09T18:15:00+05:30',
    remainingMinutes: null,
    canSendFreeform: false,
  },
  sla: { status: 'breached', deadline: '2026-08-09T20:00:00+05:30', minutesRemaining: null },
  preview: {
    text: 'I needed to ask about the exchange policy for the kurta set.',
    isIncoming: true,
    isNote: false,
    at: '2026-08-09T17:15:00+05:30',
  },
  isSpam: false,
  aiTaskCount: 0,
  firstMessageAt: '2026-08-09T11:30:00+05:30',
  lastMessageAt: '2026-08-09T17:15:00+05:30',
};

// Scenario 4: Expiring response window — Arjun Verma / Meera

export const conv_arjun_expiring: InboxConversation = {
  id: 'conv_arjun_expiring',
  contactId: 'contact_arjun_verma',
  rawMobile: null,
  whatsappNumberId: 'wa_delhi_sales',
  assigneeId: 'user_meera',
  teamId: 'team_delhi_sales',
  botOwned: false,
  status: 'open',
  unreadCount: 1,
  labelIds: ['lbl_follow_up'],
  replyStatus: 'awaiting-agent',
  responseWindow: {
    status: 'expiring',
    expiresAt: '2026-08-10T11:05:00+05:30',
    remainingMinutes: 63,
    canSendFreeform: true,
  },
  sla: { status: 'warning', deadline: '2026-08-10T10:30:00+05:30', minutesRemaining: 28 },
  preview: {
    text: 'Any update on the wallpaper samples I requested?',
    isIncoming: true,
    isNote: false,
    at: '2026-08-10T09:05:00+05:30',
  },
  isSpam: false,
  aiTaskCount: 0,
  firstMessageAt: '2026-08-08T16:00:00+05:30',
  lastMessageAt: '2026-08-10T09:05:00+05:30',
};

// Scenario 5: Failed message — Rahul Shah, second conversation

export const conv_rahul_failed: InboxConversation = {
  id: 'conv_rahul_failed',
  contactId: 'contact_rahul_shah',
  rawMobile: null,
  whatsappNumberId: 'wa_delhi_sales',
  assigneeId: 'user_meera',
  teamId: 'team_delhi_sales',
  botOwned: false,
  status: 'open',
  unreadCount: 0,
  labelIds: [],
  replyStatus: 'awaiting-customer',
  responseWindow: {
    status: 'active',
    expiresAt: '2026-08-11T07:20:00+05:30',
    remainingMinutes: 1260,
    canSendFreeform: true,
  },
  sla: { status: 'ok', deadline: '2026-08-10T16:00:00+05:30', minutesRemaining: 360 },
  preview: {
    text: 'Message failed to deliver. Tap to retry.',
    isIncoming: false,
    isNote: false,
    at: '2026-08-10T07:20:00+05:30',
  },
  isSpam: false,
  aiTaskCount: 0,
  firstMessageAt: '2026-08-10T07:00:00+05:30',
  lastMessageAt: '2026-08-10T07:20:00+05:30',
};

// Scenario 6: Bot-owned conversation — Sneha Iyer / no human assignee

export const conv_sneha_bot: InboxConversation = {
  id: 'conv_sneha_bot',
  contactId: 'contact_sneha_iyer',
  rawMobile: null,
  whatsappNumberId: 'wa_delhi_sales',
  assigneeId: null,
  teamId: null,
  botOwned: true,
  status: 'open',
  unreadCount: 0,
  labelIds: [],
  replyStatus: 'none',
  responseWindow: {
    status: 'active',
    expiresAt: '2026-08-10T21:30:00+05:30',
    remainingMinutes: 690,
    canSendFreeform: true,
  },
  sla: { status: 'ok', deadline: '2026-08-10T14:30:00+05:30', minutesRemaining: 270 },
  preview: {
    text: 'Northline Bot: Thanks for your enquiry! Collecting details…',
    isIncoming: false,
    isNote: false,
    at: '2026-08-10T09:30:00+05:30',
  },
  isSpam: false,
  aiTaskCount: 0,
  firstMessageAt: '2026-08-10T09:28:00+05:30',
  lastMessageAt: '2026-08-10T09:30:00+05:30',
};

// Scenario 7: Spam conversation — anonymous number

export const conv_spam_anon: InboxConversation = {
  id: 'conv_spam_anon',
  contactId: null,
  rawMobile: '+91 88001 55555',
  whatsappNumberId: 'wa_delhi_support',
  assigneeId: null,
  teamId: null,
  botOwned: false,
  status: 'open',
  unreadCount: 0,
  labelIds: [],
  replyStatus: 'none',
  responseWindow: {
    status: 'active',
    expiresAt: '2026-08-11T02:00:00+05:30',
    remainingMinutes: 1080,
    canSendFreeform: true,
  },
  sla: { status: 'ok', deadline: null, minutesRemaining: null },
  preview: {
    text: 'Congratulations! You have won a prize. Click here to claim.',
    isIncoming: true,
    isNote: false,
    at: '2026-08-10T02:00:00+05:30',
  },
  isSpam: true,
  aiTaskCount: 0,
  firstMessageAt: '2026-08-10T02:00:00+05:30',
  lastMessageAt: '2026-08-10T02:00:00+05:30',
};

// Scenario 8: Unassigned conversation — Arjun Verma, different number

export const conv_unassigned: InboxConversation = {
  id: 'conv_unassigned',
  contactId: 'contact_arjun_verma',
  rawMobile: null,
  whatsappNumberId: 'wa_delhi_support',
  assigneeId: null,
  teamId: null,
  botOwned: false,
  status: 'open',
  unreadCount: 3,
  labelIds: ['lbl_support'],
  replyStatus: 'awaiting-agent',
  responseWindow: {
    status: 'active',
    expiresAt: '2026-08-10T20:55:00+05:30',
    remainingMinutes: 655,
    canSendFreeform: true,
  },
  sla: { status: 'warning', deadline: '2026-08-10T10:55:00+05:30', minutesRemaining: 53 },
  preview: {
    text: 'The curtain rods I received are scratched. Need replacement ASAP.',
    isIncoming: true,
    isNote: false,
    at: '2026-08-10T08:55:00+05:30',
  },
  isSpam: false,
  aiTaskCount: 0,
  firstMessageAt: '2026-08-10T08:40:00+05:30',
  lastMessageAt: '2026-08-10T08:55:00+05:30',
};

// Scenario 9: Overloaded/unavailable assignee — Rahul Shah assigned to Rohan (busy)

export const conv_overloaded: InboxConversation = {
  id: 'conv_overloaded',
  contactId: 'contact_rahul_shah',
  rawMobile: null,
  whatsappNumberId: 'wa_delhi_sales',
  assigneeId: 'user_rohan',
  teamId: 'team_delhi_sales',
  botOwned: false,
  status: 'open',
  unreadCount: 1,
  labelIds: [],
  replyStatus: 'awaiting-agent',
  responseWindow: {
    status: 'active',
    expiresAt: '2026-08-10T19:15:00+05:30',
    remainingMinutes: 615,
    canSendFreeform: true,
  },
  sla: { status: 'ok', deadline: '2026-08-10T14:00:00+05:30', minutesRemaining: 240 },
  preview: {
    text: 'Just following up on the delivery timeline for the sofa set.',
    isIncoming: true,
    isNote: false,
    at: '2026-08-10T07:15:00+05:30',
  },
  isSpam: false,
  aiTaskCount: 0,
  firstMessageAt: '2026-08-09T14:00:00+05:30',
  lastMessageAt: '2026-08-10T07:15:00+05:30',
};

// Scenario 10: AI suggested task — Priya Menon / Anita

export const conv_ai_task: InboxConversation = {
  id: 'conv_ai_task',
  contactId: 'contact_priya_menon',
  rawMobile: null,
  whatsappNumberId: 'wa_delhi_sales',
  assigneeId: 'user_anita',
  teamId: 'team_delhi_sales',
  botOwned: false,
  status: 'open',
  unreadCount: 0,
  labelIds: ['lbl_vip', 'lbl_follow_up'],
  replyStatus: 'awaiting-customer',
  responseWindow: {
    status: 'active',
    expiresAt: '2026-08-11T10:15:00+05:30',
    remainingMinutes: 1455,
    canSendFreeform: true,
  },
  sla: { status: 'ok', deadline: '2026-08-10T18:00:00+05:30', minutesRemaining: 480 },
  preview: {
    text: "I'd love to schedule a design consultation for my new home.",
    isIncoming: true,
    isNote: false,
    at: '2026-08-09T22:15:00+05:30',
  },
  isSpam: false,
  aiTaskCount: 1,
  firstMessageAt: '2026-08-09T20:00:00+05:30',
  lastMessageAt: '2026-08-09T22:15:00+05:30',
};

// ---- All conversations in one array ---------------------------------------

export const allConversations: InboxConversation[] = [
  conv_rahul_active,
  conv_unknown_number,
  conv_priya_expired,
  conv_arjun_expiring,
  conv_rahul_failed,
  conv_sneha_bot,
  conv_spam_anon,
  conv_unassigned,
  conv_overloaded,
  conv_ai_task,
];

export function findConversation(id: string): InboxConversation | undefined {
  return allConversations.find((c) => c.id === id);
}

// ---- Messages per conversation --------------------------------------------

export const conversationMessages: Record<string, InboxMessage[]> = {
  conv_rahul_active: [
    {
      id: 'msg_ra_1',
      conversationId: 'conv_rahul_active',
      kind: 'text',
      direction: 'inbound',
      text: 'Hi, I was browsing your catalogue and wanted to enquire about the Summer Collection.',
      status: 'read',
      statusDetail: { sentAt: '2026-08-10T09:20:00+05:30', deliveredAt: '2026-08-10T09:20:05+05:30', readAt: '2026-08-10T09:21:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T09:20:00+05:30',
    },
    {
      id: 'msg_ra_2',
      conversationId: 'conv_rahul_active',
      kind: 'automated',
      direction: 'outbound',
      text: 'Thanks for reaching out to Northline Retail! A team member will be with you shortly.',
      status: 'read',
      statusDetail: { sentAt: '2026-08-10T09:20:10+05:30', deliveredAt: '2026-08-10T09:20:15+05:30', readAt: '2026-08-10T09:21:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: true,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T09:20:10+05:30',
    },
    {
      id: 'msg_ra_3',
      conversationId: 'conv_rahul_active',
      kind: 'text',
      direction: 'outbound',
      text: 'Hello Rahul! Great to hear from you. The Summer Collection is in full swing — we have fabrics, furnishings, and gift sets. What specifically are you looking at?',
      status: 'read',
      statusDetail: { sentAt: '2026-08-10T09:28:00+05:30', deliveredAt: '2026-08-10T09:28:10+05:30', readAt: '2026-08-10T09:35:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: 'user_meera',
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T09:28:00+05:30',
    },
    {
      id: 'msg_ra_4',
      conversationId: 'conv_rahul_active',
      kind: 'text',
      direction: 'inbound',
      text: 'I need around 200 units of cotton kurta fabric. We have a festive order coming up.',
      status: 'read',
      statusDetail: { sentAt: '2026-08-10T09:36:00+05:30', deliveredAt: '2026-08-10T09:36:05+05:30', readAt: '2026-08-10T09:36:30+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T09:36:00+05:30',
    },
    {
      id: 'msg_ra_note',
      conversationId: 'conv_rahul_active',
      kind: 'note',
      direction: 'outbound',
      text: '@user_vikram — Rahul is a gold customer, bulk order 200 units. Check if we can give extra 5% discount on festive pricing.',
      status: 'sent',
      statusDetail: { sentAt: '2026-08-10T09:37:00+05:30', deliveredAt: null, readAt: null, failedAt: null, failureReason: null, failureCode: null },
      sentById: 'user_meera',
      isAutomated: false,
      isNote: true,
      mentionedUserIds: ['user_vikram'],
      replyToMessageId: null,
      at: '2026-08-10T09:37:00+05:30',
    },
    {
      id: 'msg_ra_5',
      conversationId: 'conv_rahul_active',
      kind: 'text',
      direction: 'inbound',
      text: 'Can you confirm if the summer collection is still in stock?',
      status: 'delivered',
      statusDetail: { sentAt: '2026-08-10T09:42:00+05:30', deliveredAt: '2026-08-10T09:42:10+05:30', readAt: null, failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T09:42:00+05:30',
    },
  ],

  conv_unknown_9911: [
    {
      id: 'msg_un_1',
      conversationId: 'conv_unknown_9911',
      kind: 'text',
      direction: 'inbound',
      text: 'Hello, I want to place a bulk order for Diwali gifting.',
      status: 'read',
      statusDetail: { sentAt: '2026-08-10T08:10:00+05:30', deliveredAt: '2026-08-10T08:10:05+05:30', readAt: '2026-08-10T08:12:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T08:10:00+05:30',
    },
  ],

  conv_priya_expired: [
    {
      id: 'msg_pe_1',
      conversationId: 'conv_priya_expired',
      kind: 'text',
      direction: 'outbound',
      text: "Hi Priya! Hope you're enjoying the kurta set. Is there anything I can help you with?",
      status: 'read',
      statusDetail: { sentAt: '2026-08-09T11:30:00+05:30', deliveredAt: '2026-08-09T11:30:10+05:30', readAt: '2026-08-09T14:00:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: 'user_vikram',
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-09T11:30:00+05:30',
    },
    {
      id: 'msg_pe_2',
      conversationId: 'conv_priya_expired',
      kind: 'text',
      direction: 'inbound',
      text: 'I needed to ask about the exchange policy for the kurta set.',
      status: 'delivered',
      statusDetail: { sentAt: '2026-08-09T17:15:00+05:30', deliveredAt: '2026-08-09T17:15:10+05:30', readAt: null, failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-09T17:15:00+05:30',
    },
    {
      id: 'msg_pe_system',
      conversationId: 'conv_priya_expired',
      kind: 'system',
      direction: 'outbound',
      text: 'Customer message window closed (24 hours). Use a template to re-engage.',
      status: 'sent',
      statusDetail: { sentAt: '2026-08-10T17:15:00+05:30', deliveredAt: null, readAt: null, failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: true,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T17:15:00+05:30',
    },
  ],

  conv_arjun_expiring: [
    {
      id: 'msg_ae_1',
      conversationId: 'conv_arjun_expiring',
      kind: 'text',
      direction: 'inbound',
      text: 'Hi, I was in touch earlier about wallpaper options for my living room project.',
      status: 'read',
      statusDetail: { sentAt: '2026-08-08T16:00:00+05:30', deliveredAt: '2026-08-08T16:00:10+05:30', readAt: '2026-08-08T16:05:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-08T16:00:00+05:30',
    },
    {
      id: 'msg_ae_2',
      conversationId: 'conv_arjun_expiring',
      kind: 'text',
      direction: 'outbound',
      text: "Hi Arjun! Yes, I'll pull together the wallpaper samples and send them across today.",
      status: 'read',
      statusDetail: { sentAt: '2026-08-08T16:30:00+05:30', deliveredAt: '2026-08-08T16:30:10+05:30', readAt: '2026-08-09T09:00:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: 'user_meera',
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-08T16:30:00+05:30',
    },
    {
      id: 'msg_ae_3',
      conversationId: 'conv_arjun_expiring',
      kind: 'text',
      direction: 'inbound',
      text: 'Any update on the wallpaper samples I requested?',
      status: 'delivered',
      statusDetail: { sentAt: '2026-08-10T09:05:00+05:30', deliveredAt: '2026-08-10T09:05:10+05:30', readAt: null, failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T09:05:00+05:30',
    },
  ],

  conv_rahul_failed: [
    {
      id: 'msg_rf_1',
      conversationId: 'conv_rahul_failed',
      kind: 'text',
      direction: 'inbound',
      text: 'Meera, I wanted to check on the order status for my last purchase.',
      status: 'read',
      statusDetail: { sentAt: '2026-08-10T07:00:00+05:30', deliveredAt: '2026-08-10T07:00:10+05:30', readAt: '2026-08-10T07:05:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T07:00:00+05:30',
    },
    {
      id: 'msg_rf_2',
      conversationId: 'conv_rahul_failed',
      kind: 'text',
      direction: 'outbound',
      text: 'Hi Rahul! Let me check the dispatch details for you right away.',
      status: 'failed',
      statusDetail: { sentAt: null, deliveredAt: null, readAt: null, failedAt: '2026-08-10T07:20:00+05:30', failureReason: 'Message could not be delivered — WhatsApp returned error code 131026.', failureCode: '131026' },
      sentById: 'user_meera',
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T07:20:00+05:30',
    },
  ],

  conv_sneha_bot: [
    {
      id: 'msg_sb_1',
      conversationId: 'conv_sneha_bot',
      kind: 'text',
      direction: 'inbound',
      text: "Hi, I'd like to know more about your home furnishings range.",
      status: 'read',
      statusDetail: { sentAt: '2026-08-10T09:28:00+05:30', deliveredAt: '2026-08-10T09:28:05+05:30', readAt: '2026-08-10T09:28:10+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T09:28:00+05:30',
    },
    {
      id: 'msg_sb_2',
      conversationId: 'conv_sneha_bot',
      kind: 'bot',
      direction: 'outbound',
      text: "Thanks for your enquiry! I'm the Northline virtual assistant. I'll collect some details to connect you with the right team.\n\nWhich category interests you?\n1. Sofas & Seating\n2. Curtains & Blinds\n3. Wallpapers\n4. Bedding & Linen",
      status: 'delivered',
      statusDetail: { sentAt: '2026-08-10T09:28:10+05:30', deliveredAt: '2026-08-10T09:28:15+05:30', readAt: null, failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: true,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T09:28:10+05:30',
    },
    {
      id: 'msg_sb_3',
      conversationId: 'conv_sneha_bot',
      kind: 'bot',
      direction: 'outbound',
      text: 'Thanks for your enquiry! Collecting details…',
      status: 'delivered',
      statusDetail: { sentAt: '2026-08-10T09:30:00+05:30', deliveredAt: '2026-08-10T09:30:10+05:30', readAt: null, failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: true,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T09:30:00+05:30',
    },
  ],

  conv_spam_anon: [
    {
      id: 'msg_sp_1',
      conversationId: 'conv_spam_anon',
      kind: 'text',
      direction: 'inbound',
      text: 'Congratulations! You have won a prize. Click here to claim.',
      status: 'read',
      statusDetail: { sentAt: '2026-08-10T02:00:00+05:30', deliveredAt: '2026-08-10T02:00:05+05:30', readAt: '2026-08-10T09:00:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T02:00:00+05:30',
    },
  ],

  conv_unassigned: [
    {
      id: 'msg_ua_1',
      conversationId: 'conv_unassigned',
      kind: 'text',
      direction: 'inbound',
      text: 'Hello, I need help with a damaged product I received yesterday.',
      status: 'read',
      statusDetail: { sentAt: '2026-08-10T08:40:00+05:30', deliveredAt: '2026-08-10T08:40:10+05:30', readAt: '2026-08-10T08:45:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T08:40:00+05:30',
    },
    {
      id: 'msg_ua_2',
      conversationId: 'conv_unassigned',
      kind: 'text',
      direction: 'inbound',
      text: "I ordered curtain rods last week. They arrived today but they're all scratched.",
      status: 'read',
      statusDetail: { sentAt: '2026-08-10T08:48:00+05:30', deliveredAt: '2026-08-10T08:48:10+05:30', readAt: '2026-08-10T08:50:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T08:48:00+05:30',
    },
    {
      id: 'msg_ua_3',
      conversationId: 'conv_unassigned',
      kind: 'text',
      direction: 'inbound',
      text: 'The curtain rods I received are scratched. Need replacement ASAP.',
      status: 'delivered',
      statusDetail: { sentAt: '2026-08-10T08:55:00+05:30', deliveredAt: '2026-08-10T08:55:10+05:30', readAt: null, failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T08:55:00+05:30',
    },
  ],

  conv_overloaded: [
    {
      id: 'msg_ol_1',
      conversationId: 'conv_overloaded',
      kind: 'text',
      direction: 'inbound',
      text: 'Hi, checking in — any update on when the sofa set will be delivered?',
      status: 'read',
      statusDetail: { sentAt: '2026-08-09T14:00:00+05:30', deliveredAt: '2026-08-09T14:00:10+05:30', readAt: '2026-08-09T14:30:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-09T14:00:00+05:30',
    },
    {
      id: 'msg_ol_2',
      conversationId: 'conv_overloaded',
      kind: 'text',
      direction: 'outbound',
      text: "Hi Rahul! I'm checking with our dispatch team on the current status. Will update you shortly.",
      status: 'read',
      statusDetail: { sentAt: '2026-08-09T14:35:00+05:30', deliveredAt: '2026-08-09T14:35:10+05:30', readAt: '2026-08-09T15:00:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: 'user_rohan',
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-09T14:35:00+05:30',
    },
    {
      id: 'msg_ol_3',
      conversationId: 'conv_overloaded',
      kind: 'text',
      direction: 'inbound',
      text: 'Just following up on the delivery timeline for the sofa set.',
      status: 'delivered',
      statusDetail: { sentAt: '2026-08-10T07:15:00+05:30', deliveredAt: '2026-08-10T07:15:10+05:30', readAt: null, failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-10T07:15:00+05:30',
    },
  ],

  conv_ai_task: [
    {
      id: 'msg_at_1',
      conversationId: 'conv_ai_task',
      kind: 'text',
      direction: 'inbound',
      text: "Hi! I just moved into a new home and I'm looking to furnish it. Looking for premium options.",
      status: 'read',
      statusDetail: { sentAt: '2026-08-09T20:00:00+05:30', deliveredAt: '2026-08-09T20:00:10+05:30', readAt: '2026-08-09T20:10:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-09T20:00:00+05:30',
    },
    {
      id: 'msg_at_2',
      conversationId: 'conv_ai_task',
      kind: 'text',
      direction: 'outbound',
      text: "Congratulations on the new home, Priya! We'd love to help you create a beautiful space. Our premium range includes furniture, furnishings, and décor — all curated for a cohesive look.",
      status: 'read',
      statusDetail: { sentAt: '2026-08-09T20:15:00+05:30', deliveredAt: '2026-08-09T20:15:10+05:30', readAt: '2026-08-09T22:00:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: 'user_anita',
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-09T20:15:00+05:30',
    },
    {
      id: 'msg_at_3',
      conversationId: 'conv_ai_task',
      kind: 'text',
      direction: 'inbound',
      text: "I'd love to schedule a design consultation for my new home.",
      status: 'read',
      statusDetail: { sentAt: '2026-08-09T22:15:00+05:30', deliveredAt: '2026-08-09T22:15:10+05:30', readAt: '2026-08-10T09:00:00+05:30', failedAt: null, failureReason: null, failureCode: null },
      sentById: null,
      isAutomated: false,
      isNote: false,
      mentionedUserIds: [],
      replyToMessageId: null,
      at: '2026-08-09T22:15:00+05:30',
    },
  ],
};

// ---- AI Suggested Tasks ---------------------------------------------------

export const aiSuggestedTasks: AiSuggestedTask[] = [
  {
    id: 'aitask_1',
    conversationId: 'conv_ai_task',
    taskType: 'demo',
    title: 'Schedule design consultation — Priya Menon',
    description:
      'Customer explicitly requested a design consultation for her new home. High purchase intent — platinum tier customer. Suggested assignee: Anita Sharma (workspace owner).',
    sourceMessageId: 'msg_at_3',
    confidence: 'high',
    status: 'pending',
    suggestedAssigneeId: 'user_anita',
    suggestedDueAt: '2026-08-12T11:00:00+05:30',
  },
];

export function findAiTasks(conversationId: string): AiSuggestedTask[] {
  return aiSuggestedTasks.filter((t) => t.conversationId === conversationId);
}

// ---- Activity events per conversation ------------------------------------

export const conversationActivity: Record<string, ConversationActivityEvent[]> = {
  conv_rahul_active: [
    { id: 'ev_ra_1', conversationId: 'conv_rahul_active', kind: 'conversation-created', actorId: null, targetId: null, labelId: null, description: 'Conversation started via WhatsApp', at: '2026-08-10T09:20:00+05:30' },
    { id: 'ev_ra_2', conversationId: 'conv_rahul_active', kind: 'assignment', actorId: null, targetId: 'user_meera', labelId: null, description: 'Auto-assigned to Meera Nair', at: '2026-08-10T09:20:10+05:30' },
    { id: 'ev_ra_3', conversationId: 'conv_rahul_active', kind: 'label-add', actorId: 'user_meera', targetId: null, labelId: 'lbl_bulk_enquiry', description: 'Label "Bulk Enquiry" added', at: '2026-08-10T09:28:30+05:30' },
    { id: 'ev_ra_4', conversationId: 'conv_rahul_active', kind: 'label-add', actorId: 'user_meera', targetId: null, labelId: 'lbl_hot_lead', description: 'Label "Hot Lead" added', at: '2026-08-10T09:28:35+05:30' },
    { id: 'ev_ra_5', conversationId: 'conv_rahul_active', kind: 'note-added', actorId: 'user_meera', targetId: null, labelId: null, description: 'Internal note: "Rahul is interested in 200-unit order for Diwali. Follow up on pricing."', at: '2026-08-10T09:35:00+05:30' },
    { id: 'ev_ra_6', conversationId: 'conv_rahul_active', kind: 'window-expiring', actorId: null, targetId: null, labelId: null, description: 'Response window expiring in 60 minutes', at: '2026-08-10T21:42:00+05:30' },
  ],
  conv_priya_expired: [
    { id: 'ev_pe_1', conversationId: 'conv_priya_expired', kind: 'conversation-created', actorId: null, targetId: null, labelId: null, description: 'Conversation started via WhatsApp', at: '2026-08-09T16:00:00+05:30' },
    { id: 'ev_pe_2', conversationId: 'conv_priya_expired', kind: 'assignment', actorId: 'user_vikram', targetId: 'user_vikram', labelId: null, description: 'Assigned to Vikram Rao', at: '2026-08-09T16:05:00+05:30' },
    { id: 'ev_pe_3', conversationId: 'conv_priya_expired', kind: 'label-add', actorId: 'user_vikram', targetId: null, labelId: 'lbl_vip', description: 'Label "VIP" added', at: '2026-08-09T16:10:00+05:30' },
    { id: 'ev_pe_4', conversationId: 'conv_priya_expired', kind: 'window-expired', actorId: null, targetId: null, labelId: null, description: 'Response window expired — only templates can be sent', at: '2026-08-09T18:15:00+05:30' },
    { id: 'ev_pe_5', conversationId: 'conv_priya_expired', kind: 'status-pending', actorId: 'user_vikram', targetId: null, labelId: null, description: 'Status changed to Pending — awaiting customer response', at: '2026-08-10T09:00:00+05:30' },
  ],
  conv_arjun_expiring: [
    { id: 'ev_ae_1', conversationId: 'conv_arjun_expiring', kind: 'conversation-created', actorId: null, targetId: null, labelId: null, description: 'Conversation started via WhatsApp', at: '2026-08-10T09:00:00+05:30' },
    { id: 'ev_ae_2', conversationId: 'conv_arjun_expiring', kind: 'assignment', actorId: 'user_meera', targetId: 'user_meera', labelId: null, description: 'Assigned to Meera Nair', at: '2026-08-10T09:00:30+05:30' },
    { id: 'ev_ae_3', conversationId: 'conv_arjun_expiring', kind: 'label-add', actorId: 'user_meera', targetId: null, labelId: 'lbl_follow_up', description: 'Label "Follow-up" added', at: '2026-08-10T09:05:00+05:30' },
    { id: 'ev_ae_4', conversationId: 'conv_arjun_expiring', kind: 'window-expiring', actorId: null, targetId: null, labelId: null, description: 'Response window expiring — 28 minutes remaining', at: '2026-08-10T09:32:00+05:30' },
  ],
  conv_sneha_bot: [
    { id: 'ev_sb_1', conversationId: 'conv_sneha_bot', kind: 'conversation-created', actorId: null, targetId: null, labelId: null, description: 'Conversation started via WhatsApp', at: '2026-08-10T08:00:00+05:30' },
    { id: 'ev_sb_2', conversationId: 'conv_sneha_bot', kind: 'bot-started', actorId: null, targetId: null, labelId: null, description: 'Bot engaged — handling initial enquiry', at: '2026-08-10T08:00:05+05:30' },
    { id: 'ev_sb_3', conversationId: 'conv_sneha_bot', kind: 'handoff-requested', actorId: null, targetId: 'user_meera', labelId: null, description: 'Bot requested handoff to human agent', at: '2026-08-10T08:45:00+05:30' },
  ],
  conv_ai_task: [
    { id: 'ev_at_1', conversationId: 'conv_ai_task', kind: 'conversation-created', actorId: null, targetId: null, labelId: null, description: 'Conversation started via WhatsApp', at: '2026-08-09T20:00:00+05:30' },
    { id: 'ev_at_2', conversationId: 'conv_ai_task', kind: 'assignment', actorId: 'user_anita', targetId: 'user_anita', labelId: null, description: 'Assigned to Anita Sharma', at: '2026-08-09T20:05:00+05:30' },
    { id: 'ev_at_3', conversationId: 'conv_ai_task', kind: 'label-add', actorId: 'user_anita', targetId: null, labelId: 'lbl_vip', description: 'Label "VIP" added', at: '2026-08-09T20:10:00+05:30' },
    { id: 'ev_at_4', conversationId: 'conv_ai_task', kind: 'task-created', actorId: null, targetId: null, labelId: null, description: 'AI suggested follow-up task: "Schedule product demo for Karan"', at: '2026-08-09T20:15:00+05:30' },
    { id: 'ev_at_5', conversationId: 'conv_ai_task', kind: 'note-added', actorId: 'user_anita', targetId: null, labelId: null, description: 'Internal note: "Karan is a high-value VIP client — prioritise demo scheduling."', at: '2026-08-09T20:20:00+05:30' },
    { id: 'ev_at_6', conversationId: 'conv_ai_task', kind: 'reassignment', actorId: 'user_anita', targetId: 'user_rohan', labelId: null, description: 'Reassigned from Anita Sharma to Rohan Iyer', at: '2026-08-09T21:00:00+05:30' },
  ],
};

export function findActivityEvents(conversationId: string): ConversationActivityEvent[] {
  return conversationActivity[conversationId] ?? [];
}

// ---- Inbox Analytics mock ------------------------------------------------

export const inboxAnalytics: InboxAnalytics = {
  period: { from: '2026-08-01T00:00:00+05:30', to: '2026-08-10T23:59:59+05:30' },
  summary: {
    totalConversations: 312,
    responded: 289,
    resolved: 241,
    resolvedWithoutHumanResponse: 38,
    avgFirstResponseMinutes: 4,
    avgFirstHumanResponseMinutes: 7,
    avgResolutionMinutes: 142,
    unresolved: 71,
    automationUsagePercent: 62,
  },
  agentRows: [
    { userId: 'user_meera', assignedCount: 94, resolvedCount: 81, avgFirstResponseMinutes: 3, avgResolutionMinutes: 118 },
    { userId: 'user_rohan', assignedCount: 87, resolvedCount: 72, avgFirstResponseMinutes: 5, avgResolutionMinutes: 155 },
    { userId: 'user_farida', assignedCount: 78, resolvedCount: 66, avgFirstResponseMinutes: 4, avgResolutionMinutes: 138 },
    { userId: 'user_karan', assignedCount: 53, resolvedCount: 22, avgFirstResponseMinutes: 9, avgResolutionMinutes: 210 },
  ],
  conversationsByDay: [
    { date: '2026-08-01', open: 28, resolved: 24 },
    { date: '2026-08-02', open: 31, resolved: 27 },
    { date: '2026-08-03', open: 24, resolved: 22 },
    { date: '2026-08-04', open: 36, resolved: 29 },
    { date: '2026-08-05', open: 42, resolved: 35 },
    { date: '2026-08-06', open: 38, resolved: 32 },
    { date: '2026-08-07', open: 29, resolved: 26 },
    { date: '2026-08-08', open: 34, resolved: 28 },
    { date: '2026-08-09', open: 31, resolved: 18 },
    { date: '2026-08-10', open: 19, resolved: 0 },
  ],
};
